export const API_CONFIG = {
  SIGHTENGINE_API_USER: '857350597',
  SIGHTENGINE_API_SECRET: 'FY26G7aeho3NAcS4XXzqpPypWQ2SSsd5',
  SIGHTENGINE_URL: 'https://api.sightengine.com/1.0/check.json',
  CONFIDENCE_THRESHOLD: 0.7
}; 